from __future__ import annotations

import json
import tempfile
import unittest
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path

from runbook_generator.cli import main


class OpsPackageTests(unittest.TestCase):
    def test_ops_package_writes_agent_and_platform_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "ops"

            with redirect_stdout(StringIO()):
                exit_code = main(
                    [
                        "ops-package",
                        "--source",
                        "fixture",
                        "--environment",
                        "test-environment",
                        "--region",
                        "test-region",
                        "--cluster",
                        "test-cluster",
                        "--namespace",
                        "test-namespace",
                        "--service",
                        "test-service",
                        "--output-dir",
                        str(output_dir),
                        "--observability-provider",
                        "test-observability",
                        "--observability-dashboard-url",
                        "https://observability.example.invalid/dashboard",
                        "--jira-base-url",
                        "https://jira.example.invalid",
                        "--jira-project-key",
                        "OPS",
                        "--confluence-base-url",
                        "https://confluence.example.invalid",
                        "--confluence-space-key",
                        "OPS",
                        "--wiki-base-url",
                        "https://wiki.example.invalid",
                    ]
                )

            self.assertEqual(exit_code, 0)
            expected_files = {
                "agent_context.json",
                "confluence_page.json",
                "incident_report.md",
                "jira_issue.json",
                "observability_signals.json",
                "runbook.md",
                "snapshot.json",
                "wiki_page.md",
            }
            self.assertEqual(
                expected_files,
                {path.name for path in output_dir.iterdir()},
            )

            agent_context = json.loads(
                (output_dir / "agent_context.json").read_text()
            )
            jira_payload = json.loads((output_dir / "jira_issue.json").read_text())
            confluence_payload = json.loads(
                (output_dir / "confluence_page.json").read_text()
            )

            self.assertEqual(
                agent_context["schema"],
                "runbook-generator.agent-context.v1",
            )
            self.assertIn("wiki_page", agent_context["artifacts"])
            self.assertIn("jira_payload", agent_context["artifacts"])
            self.assertIn("confluence_payload", agent_context["artifacts"])
            self.assertEqual(
                jira_payload["destination"]["project_key"],
                "OPS",
            )
            self.assertEqual(
                confluence_payload["destination"]["space_key"],
                "OPS",
            )
            self.assertIn(
                "Generated by Runbook Generator",
                (output_dir / "wiki_page.md").read_text(),
            )


if __name__ == "__main__":
    unittest.main()
