"""Generic wiki Markdown renderer."""

from __future__ import annotations

from dataclasses import dataclass

from runbook_generator.agent.models import IncidentReport


@dataclass(frozen=True, slots=True)
class WikiTarget:
    """Generic wiki destination metadata."""

    base_url: str | None


class WikiExporter:
    """Render a Markdown wiki page teams can publish or review."""

    def __init__(self, target: WikiTarget) -> None:
        self.target = target

    def render_page(self, report: IncidentReport, runbook_markdown: str) -> str:
        lines = [
            "---",
            f"title: {report.title}",
            f"environment: {report.environment}",
            f"service: {report.service or 'unknown'}",
            f"severity: {report.severity}",
            f"generated_at: {report.generated_at}",
            f"wiki_base_url: {self.target.base_url or 'not_configured'}",
            "---",
            "",
            "# Team Runbook",
            "",
            "> Generated by Runbook Generator. Validate before publishing.",
            "",
            "## Incident/report context",
            "",
            report.summary,
            "",
            "## Recommended actions",
            "",
        ]
        lines.extend([f"{index}. {action}" for index, action in enumerate(report.recommended_actions, 1)])
        lines.extend(["", "## Runbook", "", runbook_markdown])
        return "\n".join(lines).rstrip() + "\n"
